baseurl = "/"
languageCode = "en-us"
title = "buglessdevelopment"
theme = "hugo-classic"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "â†©"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[params]
    description = "A new, better development methodology"
    footer = "[Github](https://github.com/bugless)"
